### ISSUE TITLE
Breakout boards and Molex Keyboard Connectors

### ISSUE THREAD

**Issue by jstjst** [basketofkittens/framework701c#2]
Hi @basketofkittens,

I saw your project on the framework forum and I'm about to start a 701c conversion (I will probably put a Raspberry Pi in it).
Do you still have some Keyboard Breakout boards and the Molex connectors?

May I ask where you are based? The 50$ shipping cost to Germany from Quest Components just for the Molex connectors seems ridiculous to me.

Jonas

**Comment by basketofkittens** [comment]
I believe I still have some of both. I'm located in Los Angeles, on the west coast of America. Can I send you an email at the address on your profile?

**Comment by jstjst** [comment]
Yes you can send me an email to that address. Are there any other components that are needed to interface with the thinkpad side? Did you get the Trackpoint module directly from Sprintek?
